name: mon_essaye_riverpod
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter_hooks: 0.18.5+1
  hooks_riverpod: 2.1.3
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  cloud_firestore: 4.3.1
  fake_cloud_firestore: 2.3.0+3
  go_router: 6.0.1
  intl: ^0.17.0
  rxdart: 0.27.7
  equatable: 2.0.5
  flutter_svg: 1.1.6
  shared_preferences: 2.0.16
  envied: 0.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  build_runner: 2.3.3
  envied_generator: 0.3.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/.env
  uses-material-design: true

